[build]
    publish = "/build"
    command = "CI=false yarn build"
    functions = "functions"
[[redirects]]
    from = "https://keen-dijkstra-382f3a.netlify.app/api/*"
    to = "./netlify/functions/:splat"
    status = 200
